language: c

jobs:
  include:
    - os: macos
      script: sh ./build-macos.sh
      compiler: clang

    - os: linux
      script: dpkg-buildpackage -b -us -uc
      compiler: gcc
      install:
        - sudo apt-get install libgmp-dev
        - sudo apt-get install fakeroot
        - sudo apt-get install debhelper
	- sudo apt-get install texlive-binaries
	- sudo apt-get install texlive-latex-base
	- sudo apt-get install fig2ps

#    - os: linux
#      compiler: clang
#      script: dpkg-buildpackage -b -us -uc
#      install:
#        - sudo apt-get install libgmp-dev
#        - sudo apt-get install fakeroot
#        - sudo apt-get install debhelper

# whitelist
branches:
   only:
      - master
      - /.*\/staging/
      - /.*\/travis/
