#!/usr/bin/env perl

use common::sense;
use Storable;
use Data::Dumper;
use JSON::XS;

$Data::Dumper::Indent = 1;
$Data::Dumper::Terse = 1;

my $log = retrieve 'evaluator.pst';
# transform a bit for readability
my @log = map { {
   # Time stamp.
   time => $log->{$_}[0],
   # Processing time.
   proc => $log->{$_}[1],
   # Client host.
   host => $log->{$_}[2],
   # REPL line.
   line => $log->{$_}[3],
   # Source code.
   code => [split "\n", $_],
} } keys %$log;

print Dumper \@log;
