sit_gcdint_deps := sit_modgcd sit_heugcd
sit_gcdintg_deps := sit_modgcd sit_heugcd
sit_heugcd_deps :=
sit_modgcd_deps := sit_modpgcd
sit_modpgcd_deps :=

library_deps := util numbers extree extree/operators extree/parser \
	        categories basic mat mat/gauss mat/modular mat/modular \
	        mat/modular/compbug mat/linalg univpoly/categories \
	        mat/linalg2 multpoly/multpolydata univpoly
