#ifndef TESTALL_H
#define TESTALL_H

void abcheckTest(void);
void ablogTest(void);
void abnormTest(void);
void absynTest(void);
void annotateAbSynTest(void);
void archiveTestSuite(void);
void bigintTestSuite(void);
void bintTestSuite(void);
void bitvTestSuite(void);
void errorSetTestSuite(void);
void floatTestSuite(void);
void flogTest(void);
void fnameTest(void);
void foamTest(void);
void forgTest(void);
void formatTest(void);
void fptrTest(void);
void genfoamTestSuite(void);
void intTestSuite(void);
void javaTestSuite(void);
void jcodeTest(void);
void jflowTest(void);
void listTestSuite(void);
void ostreamTest(void);
void ofPeepTest(void);
void ofCPropTest(void);
void printfTest(void);
void retypeTest(void);
void scobindTest(void);
void srcposTest(void);
void stabTest(void);
void stropsTestSuite(void);
void symeTest(void);
void symeSetTestSuite(void);
void tformTest(void);
void tfsatTest(void);
void tibupTest(void);
void tinferTest(void);
void tpossTest(void);
void tsetTestSuite(void);

#endif
