library_deps := util extree extree/operators extree/parser numbers categories basic

tst_assert_deps := 
tst_test_deps := tst_assert
tst_complex_deps := tst_assert tst_test
tst_random_deps := tst_assert tst_test
