aldorug.pdf:
	pdflatex aldorug
	makeindex aldorug
	pdflatex aldorug
	pdflatex aldorug

clean:
	-rm aldorug.aux aldorug.idx aldorug.ilg aldorug.ind aldorug.lof
	-rm aldorug.out aldorug.pdf aldorug.toc
