/*****************************************************************************
 *
 * comsgdb.h: Generated from comsgdb.msg
 *
 * Copyright (c) 1990-2007 Aldor Software Organization Ltd (Aldor.org).
 *
 *****************************************************************************/

#ifndef _comsgdb_MSG_H_
#define _comsgdb_MSG_H_

#include "msg.h"

/* Last member has setno == -1. */

extern struct msgInfo comsgdb_msgs[];


/* Messages for set ALDOR_GROUP = 1 */
# define ALDOR_GROUP 1

# define ALDOR_E_ExplicitMsg 1
# define ALDOR_N_ExplicitMsg 2
# define ALDOR_N_Here 3
# define ALDOR_F_CmdBadOption 4
# define ALDOR_F_CmdNoOption 5
# define ALDOR_F_CmdCantUseEntry 6
# define ALDOR_F_CmdNoOutputDir 7
# define ALDOR_W_CmdFunnyEntry 8
# define ALDOR_W_DisableNotKeyword 9
# define ALDOR_W_FtnVarStringRet 10
# define ALDOR_W_FtnNotFtnArg 11
# define ALDOR_F_MsgTooManyErrors 12
# define ALDOR_R_MsgCountMessages 13
# define ALDOR_R_MsgAdviseDetails 14
# define ALDOR_R_MsgCondolences 15
# define ALDOR_R_MsgCongratulations 16
# define ALDOR_P_MsgTagRemark 17
# define ALDOR_P_MsgTagWarning 18
# define ALDOR_P_MsgTagError 19
# define ALDOR_P_MsgTagFatal 20
# define ALDOR_P_MsgTagNote 21
# define ALDOR_P_MsgPreview 22
# define ALDOR_P_MsgAfterMacEx 23
# define ALDOR_P_MsgExpandedExpr 24
# define ALDOR_P_MsgSposFileLine 25
# define ALDOR_P_MsgSposLineChar 26
# define ALDOR_P_MsgNote 27
# define ALDOR_P_MsgSeeNote 28
# define ALDOR_P_MsgCfNote 29
# define ALDOR_P_MsgCfFarNote 30
# define ALDOR_P_MsgConjunction 31
# define ALDOR_E_InclBadUnassert 32
# define ALDOR_E_InclIfEof 33
# define ALDOR_E_InclInfinite 34
# define ALDOR_E_InclUnbalElse 35
# define ALDOR_E_InclUnbalElseif 36
# define ALDOR_E_InclUnbalEndif 37
# define ALDOR_W_OldOptMain 38
# define ALDOR_W_OldOptAbsyn 39
# define ALDOR_W_OldTypeAbsyn 40
# define ALDOR_W_OldMsgPrefix 41
# define ALDOR_E_SysCmdBad 42
# define ALDOR_W_SysCmdUnknown 43
# define ALDOR_E_ScanBadAftRad 44
# define ALDOR_E_ScanBadChar 45
# define ALDOR_E_ScanBadExpon 46
# define ALDOR_E_ScanBadRadix 47
# define ALDOR_E_ScanNoDigits 48
# define ALDOR_E_ScanOpenString 49
# define ALDOR_E_NormMacDecl 50
# define ALDOR_E_NormMacBadBody 51
# define ALDOR_W_NormNoId 52
# define ALDOR_W_NormFornForeign 53
# define ALDOR_W_NormFornBuiltin 54
# define ALDOR_W_NormNullForeign 55
# define ALDOR_E_MacBadDefn 56
# define ALDOR_E_MacBadParam 57
# define ALDOR_E_MacBadParamDecl 58
# define ALDOR_E_MacBadArgc 59
# define ALDOR_E_MacBadArg 60
# define ALDOR_E_MacInfinite 61
# define ALDOR_W_MacHides 62
# define ALDOR_W_MacRedefined 63
# define ALDOR_F_SyntaxOverflow 64
# define ALDOR_E_SyntaxError 65
# define ALDOR_E_SyntaxErrorDebug 66
# define ALDOR_E_SyntaxErrorHuh 67
# define ALDOR_E_SyntaxNoRecovery 68
# define ALDOR_E_SyntaxFullError 69
# define ALDOR_E_LinUnbalanced 70
# define ALDOR_W_LinUnbalanced 71
# define ALDOR_F_LoadNotAbSyn 72
# define ALDOR_F_LoadNotFoam 73
# define ALDOR_F_LoadNotList 74
# define ALDOR_F_LoadNotUnary 75
# define ALDOR_F_LoadNotString 76
# define ALDOR_F_LoadNotSymbol 77
# define ALDOR_F_LoadNotInteger 78
# define ALDOR_F_LoadNotFloat 79
# define ALDOR_W_CantUnKeywordRef 80
# define ALDOR_E_ChkBadAssign 81
# define ALDOR_E_ChkBadDeclare 82
# define ALDOR_E_ChkBadDefine 83
# define ALDOR_W_ChkBadDependent 84
# define ALDOR_E_ChkBadFor 85
# define ALDOR_E_ChkBadForm 86
# define ALDOR_E_ChkBadGoto 87
# define ALDOR_E_ChkBadLabel 88
# define ALDOR_E_ChkBadMLambda 89
# define ALDOR_E_ChkBadMacro 90
# define ALDOR_E_ChkBadParams 91
# define ALDOR_E_ChkBadParamsDups 92
# define ALDOR_E_ChkBadQualification 93
# define ALDOR_E_ChkBadRecordOrUnion 94
# define ALDOR_E_ChkMissingRetType 95
# define ALDOR_D_ChkUseFromHint 96
# define ALDOR_E_ChkSelectSeq 97
# define ALDOR_E_ChkSelectExits 98
# define ALDOR_W_FunnyJuxta 99
# define ALDOR_W_FunnyColon 100
# define ALDOR_W_FunnyEquals 101
# define ALDOR_W_FunnyEscape 102
# define ALDOR_W_OldSyntaxAlways 103
# define ALDOR_W_OldSyntaxCatch 104
# define ALDOR_W_OldSyntaxThrow 105
# define ALDOR_W_OldSyntaxUnknown 106
# define ALDOR_W_AbnDomainWithout 107
# define ALDOR_E_ScoAssAndDef 108
# define ALDOR_E_ScoAssAndRef 109
# define ALDOR_E_ScoAssTypeId 110
# define ALDOR_E_ScoBadLexConst 111
# define ALDOR_E_ScoFluidShadow 112
# define ALDOR_E_ScoBadLoopAss 113
# define ALDOR_E_ScoBadParameter 114
# define ALDOR_E_ScoBadTypeFree 115
# define ALDOR_E_ScoDupDefine 116
# define ALDOR_E_ScoFreeAndLoc 117
# define ALDOR_E_ScoFreeConst 118
# define ALDOR_E_ScoLateFreeLocal 119
# define ALDOR_E_ScoLibrary 120
# define ALDOR_E_ScoNoFree 121
# define ALDOR_E_ScoNoParm 122
# define ALDOR_E_ScoNoSet 123
# define ALDOR_E_ScoNotBuiltin 124
# define ALDOR_E_ScoParmLocFree 125
# define ALDOR_E_ScoSameSig 126
# define ALDOR_E_ScoParmType 127
# define ALDOR_E_ScoVarOverload 128
# define ALDOR_E_ScoUnknownFree 129
# define ALDOR_W_ScoNotProtocol 130
# define ALDOR_W_ScoBadLocal 131
# define ALDOR_W_ScoFunnyUse 132
# define ALDOR_W_ScoBadUse 133
# define ALDOR_W_ScoLocalNoUse 134
# define ALDOR_W_ScoVarDefault 135
# define ALDOR_R_ScoMeaning 136
# define ALDOR_E_ScoEarlyUse 137
# define ALDOR_E_StabDupLabels 138
# define ALDOR_R_StabImporting 139
# define ALDOR_R_StabImportingQual 140
# define ALDOR_W_StabNotImporting 141
# define ALDOR_F_LibOutOfDate 142
# define ALDOR_F_LibBadVersion 143
# define ALDOR_F_LibExportNotFound 144
# define ALDOR_E_LibBadMagic 145
# define ALDOR_E_LibBadNumSect 146
# define ALDOR_E_LibBadSectHdr 147
# define ALDOR_E_LibBadSectName 148
# define ALDOR_E_LibSectDup 149
# define ALDOR_E_LibSectLimit 150
# define ALDOR_E_LibSectOffset 151
# define ALDOR_W_LibRedefined 152
# define ALDOR_E_ArTruncated 153
# define ALDOR_E_ArBadNumber 154
# define ALDOR_E_TinNoMeaningForId 155
# define ALDOR_E_TinNoMeaningForLit 156
# define ALDOR_E_TinBadDeclare 157
# define ALDOR_E_TinIfMeans 158
# define ALDOR_E_TinAssMeans 159
# define ALDOR_E_TinDefnMeans 160
# define ALDOR_E_TinCantSplitRHS 161
# define ALDOR_E_TinAssignCreatesDepType 162
# define ALDOR_E_TinExprMeans 163
# define ALDOR_E_TinNMeanings 164
# define ALDOR_E_TinBadGoto 165
# define ALDOR_E_TinFarGoto 166
# define ALDOR_E_TinOpMeans 167
# define ALDOR_E_TinWildExit 168
# define ALDOR_E_TinWildReturn 169
# define ALDOR_E_TinWildYield 170
# define ALDOR_E_TinContext 171
# define ALDOR_E_TinContextAssert 172
# define ALDOR_E_TinContextDo 173
# define ALDOR_E_TinContextExit 174
# define ALDOR_E_TinContextIf 175
# define ALDOR_E_TinContextRepeat 176
# define ALDOR_E_TinContextSeq 177
# define ALDOR_E_TinCantInferLhs 178
# define ALDOR_E_TinNoGoodOp 179
# define ALDOR_E_TinNoGoodInterp 180
# define ALDOR_E_TinFirstExitType 181
# define ALDOR_E_TinFirstExitTypes 182
# define ALDOR_E_TinTypeConstIntro 183
# define ALDOR_X_TinTypeConstFailed 184
# define ALDOR_E_TinCantBeAnalyzed 185
# define ALDOR_E_TinEmbeddedSet 186
# define ALDOR_E_TinMultiTry 187
# define ALDOR_E_TinPackedNotSat 188
# define ALDOR_D_TinNoGoodInterp 189
# define ALDOR_D_TinNoMeaningForId 190
# define ALDOR_D_TinSubexprMeans 191
# define ALDOR_D_TinPossTypesLhs 192
# define ALDOR_D_TinPossTypes 193
# define ALDOR_D_TinPossInterps 194
# define ALDOR_D_TinPossTypesRhs 195
# define ALDOR_D_TinAlternativeMeanings 196
# define ALDOR_D_TinOneMeaning 197
# define ALDOR_D_TinContextType 198
# define ALDOR_D_TinMissingExports 199
# define ALDOR_D_TinMissingExport 200
# define ALDOR_D_TinRejectedTypes 201
# define ALDOR_X_TinNoArgumentMatch 202
# define ALDOR_X_TinParameterMissing 203
# define ALDOR_X_TinBadArgumentNumber 204
# define ALDOR_X_TinBadFnType 205
# define ALDOR_D_TinRejectedType 206
# define ALDOR_D_TinRejectedTypesForRhs 207
# define ALDOR_D_TinRejectedTypeForRhs 208
# define ALDOR_D_TinShouldUseDoubleEq 209
# define ALDOR_D_TinAvailableTypesForArg 210
# define ALDOR_D_TinArgNoMatchParTypes 211
# define ALDOR_D_TinOperatorNoMatch 212
# define ALDOR_D_TinMoreMeanings 213
# define ALDOR_D_TinRetTypesCantContext 214
# define ALDOR_D_TinExpectedType 215
# define ALDOR_D_TinExpectedTypes 216
# define ALDOR_D_TinRejectedRetTypes 217
# define ALDOR_D_TinOtherDiffArgNum 218
# define ALDOR_D_TinPossSelectorTypes 219
# define ALDOR_D_TinPossRetTypeSetBang 220
# define ALDOR_D_TinPossTypesForSetBang 221
# define ALDOR_D_TinSetBangBadArgNum 222
# define ALDOR_D_TinOneImpMeaning 223
# define ALDOR_D_TinOneLexMeaning 224
# define ALDOR_D_TinOneLibMeaning 225
# define ALDOR_D_TinOneMeaning0 226
# define ALDOR_D_TinFirstExitCant 227
# define ALDOR_N_TinOtherExitType 228
# define ALDOR_N_TinOtherExitTypes 229
# define ALDOR_W_TinNoValReturn 230
# define ALDOR_E_TinReturnNoVal 231
# define ALDOR_F_TinRestrictOops 232
# define ALDOR_R_TinInferring 233
# define ALDOR_W_TqNotBuiltin 234
# define ALDOR_E_GenImpNoRep 235
# define ALDOR_W_GenDomFunNotConst 236
# define ALDOR_W_GenCatFunNotConst 237
# define ALDOR_W_GenBadDefCycle 238
# define ALDOR_W_GenBadDefOrder 239
# define ALDOR_M_FintBreakHandler 240
# define ALDOR_M_FintBreakHandler0 241
# define ALDOR_M_FintYesOrNo 242
# define ALDOR_M_FintRedefined 243
# define ALDOR_M_FintOptionState 244
# define ALDOR_M_FintOptionValue 245
# define ALDOR_M_FintUnknownOpt 246
# define ALDOR_M_FintTimings 247
# define ALDOR_M_FintGbcStart 248
# define ALDOR_M_FintGbcEnd 249
# define ALDOR_M_FintIntOptionsNoFile 250
# define ALDOR_M_ShellSyntax 251
# define ALDOR_M_CdSyntax 252
# define ALDOR_M_InvalidDir 253
# define ALDOR_M_FintOptions 254
# define ALDOR_F_CdFailed 255
# define ALDOR_F_CcFailed 256
# define ALDOR_F_LinkFailed 257
# define ALDOR_F_BadFType 258
# define ALDOR_F_WdClobberIn 259
# define ALDOR_F_WdClobberFile 260
# define ALDOR_W_WillObsolete 261
# define ALDOR_W_RemovingFile 262
# define ALDOR_W_NotCreatingFile 263
# define ALDOR_W_NoFiles 264
# define ALDOR_F_NoConfig 265
# define ALDOR_W_CfgError 266
# define ALDOR_F_NoFNameProperty 267
# define ALDOR_F_BadFNameValue 268
# define ALDOR_F_NoFCmplxProperty 269
# define ALDOR_F_BadFCmplxValue 270
# define ALDOR_M_BreakEnter 271
# define ALDOR_M_BreakExit 272
# define ALDOR_M_BreakNoMsg 273
# define ALDOR_M_BreakNoCmd 274
# define ALDOR_M_BreakMsgPrompt 275
# define ALDOR_M_BreakMsgHelpAvail 276
# define ALDOR_M_BreakMsgBadNode 277
# define ALDOR_M_BreakMsgNoNode 278
# define ALDOR_M_BreakMsgNoStab 279
# define ALDOR_M_BreakMsgNoTypeInfo 280
# define ALDOR_M_BreakMsgAtTop 281
# define ALDOR_M_BreakMsgAtLeaf 282
# define ALDOR_M_BreakMsgNoPrev 283
# define ALDOR_M_BreakMsgNoNext 284
# define ALDOR_M_BreakMsgCantSelect 285
# define ALDOR_M_BreakMsgNTypes 286
# define ALDOR_M_BreakMsg1Type 287
# define ALDOR_M_BreakMsgUsedContext 288
# define ALDOR_M_BreakMsgNotId 289
# define ALDOR_M_BreakHelp 290
# define ALDOR_M_GloopBanner 291
# define ALDOR_H_HelpCmd 292
# define ALDOR_H_HelpFileTypes 293
# define ALDOR_H_HelpOptionSummary 294
# define ALDOR_H_HelpHelpOpt 295
# define ALDOR_H_HelpArgOpt 296
# define ALDOR_H_HelpDirOpt 297
# define ALDOR_H_HelpFileOpt 298
# define ALDOR_H_HelpGoOpt 299
# define ALDOR_H_HelpOptimOpt 300
# define ALDOR_H_HelpDebugOpt 301
# define ALDOR_H_HelpConfigOpt 302
# define ALDOR_H_HelpCOpt 303
# define ALDOR_H_HelpCppOpt 304
# define ALDOR_H_HelpLispOpt 305
# define ALDOR_H_HelpMsgOpt 306
# define ALDOR_H_HelpDevOpt 307
# define ALDOR_H_HelpMenuPointer 308
# define ALDOR_H_HelpProductInfo 309
# define ALDOR_E_SigAbrt 310
# define ALDOR_E_SigBus 311
# define ALDOR_E_SigEmt 312
# define ALDOR_E_SigFpe 313
# define ALDOR_E_SigHup 314
# define ALDOR_E_SigIll 315
# define ALDOR_E_SigInt 316
# define ALDOR_E_SigPipe 317
# define ALDOR_E_SigDanger 318
# define ALDOR_E_SigQuit 319
# define ALDOR_E_SigSegv 320
# define ALDOR_E_SigSys 321
# define ALDOR_E_SigTerm 322
# define ALDOR_E_SigTrap 323
# define ALDOR_E_SigXcpu 324
# define ALDOR_E_SigXfsz 325
# define ALDOR_E_SigUnknown 326
# define ALDOR_F_SxAlreadyShare 327
# define ALDOR_F_SxBadArgumentTo 328
# define ALDOR_F_SxBadChar 329
# define ALDOR_F_SxBadCharName 330
# define ALDOR_F_SxBadComplexNum 331
# define ALDOR_F_SxBadFeatureForm 332
# define ALDOR_F_SxBadPotNum 333
# define ALDOR_F_SxBadPunct 334
# define ALDOR_F_SxBadToken 335
# define ALDOR_F_SxBadUninterned 336
# define ALDOR_F_SxCantMacroArg 337
# define ALDOR_F_SxCantShare 338
# define ALDOR_F_SxInternNeeds 339
# define ALDOR_F_SxMacroIlleg 340
# define ALDOR_F_SxMacroUndef 341
# define ALDOR_F_SxMacroUnimp 342
# define ALDOR_F_SxMustMacroArg 343
# define ALDOR_F_SxNReverseNeeds 344
# define ALDOR_F_SxNumDenNeeds 345
# define ALDOR_F_SxPackageExists 346
# define ALDOR_F_SxReadEOF 347
# define ALDOR_F_SxTooManyElts 348
# define ALDOR_F_StoCantBuild 349
# define ALDOR_F_StoOutOfMemory 350
# define ALDOR_F_StoUsedNonalloc 351
# define ALDOR_F_StoFreeBad 352
# define ALDOR_F_CantOpen 353
# define ALDOR_F_CantOpenMode 354
# define ALDOR_F_CantFindTemp 355
# define ALDOR_W_CantUseObject 356
# define ALDOR_W_CantUseLibrary 357
# define ALDOR_W_CantUseArchive 358
# define ALDOR_W_OverRideLibraryFile 359
# define ALDOR_F_Bug 360
# define ALDOR_W_Bug 361
# define ALDOR_F_BugNoBoolean 362
# define ALDOR_F_BugExportSymeNotInit 363
# define ALDOR_I_PreRelease 364
# define ALDOR_I_DemoExpiry 365
# define ALDOR_S_Syme_Label 366
# define ALDOR_S_Syme_Param 367
# define ALDOR_S_Syme_LexVar 368
# define ALDOR_S_Syme_LexConst 369
# define ALDOR_S_Syme_Import 370
# define ALDOR_S_Syme_Export 371
# define ALDOR_S_Syme_Extend 372
# define ALDOR_S_Syme_Library 373
# define ALDOR_S_Syme_Archive 374
# define ALDOR_S_Syme_Builtin 375
# define ALDOR_S_Syme_Foreign 376
# define ALDOR_S_Syme_Fluid 377
# define ALDOR_S_Syme_Trigger 378
# define ALDOR_S_Syme_Temp 379

#endif
