#ifndef GF_MATCH0_H
#define GF_MATCH0_H

extern void gfm0MatchExpr(AbSyn, Foam); // Recursive call...
extern Foam gfm0MatchExit(void); // Recursive call...
extern AInt gfm0MatchExitLabel(void); // Recursive call...

#endif
