library_deps := util

bs_deps :=
tform_deps := bs
tform_types_deps := tform
tform_atoms_deps := tform
tform_syntax_deps := tform
tform_map_deps := tform
tform_cat_deps := tform
tform_sat_deps := tform_types tform_atoms tform_syntax tform_map tform_cat
