/*...
(nlseq
  (statement (spaceseq "import" (importid "foamj" "EnvRecord")))
  (statement (spaceseq "import" (importid "foamj" "Record")))
  (statement (spaceseq "import" (importid "foamj" "Format")))
  (statement (spaceseq "import" (importid "foamj" "Word")))
  (statement (spaceseq "import" (importid "foamj" "Value")))
  (statement (spaceseq "import" (importid "foamj" "Env")))
  (statement (spaceseq "import" (importid "foamj" "Clos")))
  (statement (spaceseq "import" (importid "foamj" "Globals")))
  (statement (spaceseq "import" (importid "foamj" "Fn")))
  (nlseq
    (javadoc "Generated by genjava - rectest\\\\n")
    (class
      (spaceseq public)
      "rectest"
      ()
      (commaseq)
      (nlseq
        (statement
          (declaration
            (spaceseq private static)
            (importid "foamj" "Format")
            (assign
              "FORMAT_5"
              (new (apply (importid "foamj" "Format") (paren (commaseq 3))) ()))))
        (statement
          (declaration
            (spaceseq private static)
            (importid "foamj" "Format")
            (assign
              "FORMAT_6"
              (new (apply (importid "foamj" "Format") (paren (commaseq 1))) ()))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C0_rectest"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement (apply "c0_rectest" (paren (commaseq "env"))))
                        (statement (spaceseq return null)))))))))
          (method
            (declaration
              (spaceseq private static)
              void
              "c0_rectest"
              (paren
                (commaseq (declaration (spaceseq) (importid "foamj" "Env") "env0")))
              (commaseq))
            (nlseq
              (statement
                (declaration
                  (spaceseq)
                  (spaceseq (importid "foamj" "Word") (sqbracket (spaceseq)))
                  (commaseq "t1")))
              (statement
                (declaration
                  (spaceseq)
                  (importid "foamj" "Record")
                  (commaseq "t2" "t3")))
              (statement
                (declaration
                  (spaceseq)
                  (spaceseq int (sqbracket (spaceseq)))
                  (commaseq "t0")))
              (nlseq
                (statement
                  (apply
                    "ccall_Xx"
                    (paren
                      (commaseq
                        (apply
                          (memref
                            (apply
                              (memref (importid "foamj" "Globals") "getGlobal")
                              (paren (commaseq "runtime")))
                            "toClos")
                          (paren (commaseq)))))))
                (statement
                  (apply
                    (memref (importid "foamj" "Globals") "setGlobal")
                    (paren
                      (commaseq
                        "rectest"
                        (apply
                          (memref
                            (apply
                              (memref (importid "foamj" "Globals") "getGlobal")
                              (paren (commaseq "noOperation")))
                            "toClos")
                          (paren (commaseq)))))))
                (statement
                  (apply
                    (memref (importid "foamj" "Globals") "setGlobal")
                    (paren
                      (commaseq
                        "rectest_Rec_743553378"
                        (apply
                          (memref
                            (apply
                              "ccall_WxC"
                              (paren
                                (commaseq
                                  (apply
                                    (memref
                                      (apply
                                        (memref (importid "foamj" "Globals") "getGlobal")
                                        (paren (commaseq "domainMake")))
                                      "toClos")
                                    (paren (commaseq)))
                                  (new
                                    (apply
                                      (importid "foamj" "Clos")
                                      (paren (commaseq "env0" "C1_addLevel0")))
                                    ()))))
                            "toValue")
                          (paren (commaseq)))))))
                (statement (assign "t0" (new (arrayref int 2) ())))
                (statement
                  (assign "t1" (new (arrayref (importid "foamj" "Word") 2) ())))
                (statement (assign (arrayref "t0" 0) 318528389))
                (statement
                  (assign
                    (arrayref "t1" 0)
                    (apply (memref "new" "toCharArray") (paren (commaseq)))))
                (statement (assign (arrayref "t0" 1) 315787127))
                (statement
                  (assign
                    (arrayref "t1" 1)
                    (apply (memref "tag" "toCharArray") (paren (commaseq)))))
                (statement
                  (assign
                    "t2"
                    (new
                      (apply (importid "foamj" "Record") (paren (commaseq "FORMAT_5")))
                      ())))
                (statement
                  (apply
                    (memref "t2" "setField")
                    (paren
                      (commaseq
                        0
                        "size"
                        (apply
                          (memref (memref (importid "foamj" "Value") "U") "fromSInt")
                          (paren (commaseq 2)))))))
                (statement
                  (apply
                    (memref "t2" "setField")
                    (paren
                      (commaseq
                        1
                        "nsize"
                        (apply
                          (memref (memref (importid "foamj" "Value") "U") "fromSInt")
                          (paren (commaseq 2)))))))
                (statement
                  (apply
                    (memref "t2" "setField")
                    (paren
                      (commaseq
                        2
                        "values"
                        (apply
                          (memref
                            (cast (spaceseq (importid "foamj" "Word") (comment "Arr")) "t0")
                            "toValue")
                          (paren (commaseq)))))))
                (statement
                  (assign
                    "t3"
                    (new
                      (apply (importid "foamj" "Record") (paren (commaseq "FORMAT_5")))
                      ())))
                (statement
                  (apply
                    (memref "t3" "setField")
                    (paren
                      (commaseq
                        0
                        "size"
                        (apply
                          (memref (memref (importid "foamj" "Value") "U") "fromSInt")
                          (paren (commaseq 2)))))))
                (statement
                  (apply
                    (memref "t3" "setField")
                    (paren
                      (commaseq
                        1
                        "nsize"
                        (apply
                          (memref (memref (importid "foamj" "Value") "U") "fromSInt")
                          (paren (commaseq 2)))))))
                (statement
                  (apply
                    (memref "t3" "setField")
                    (paren
                      (commaseq
                        2
                        "values"
                        (apply
                          (memref
                            (cast (spaceseq (importid "foamj" "Word") (comment "Arr")) "t1")
                            "toValue")
                          (paren (commaseq)))))))
                (statement
                  (apply
                    "ccall_XxWW"
                    (paren
                      (commaseq
                        (apply
                          (memref
                            (apply
                              (memref (importid "foamj" "Globals") "getGlobal")
                              (paren (commaseq "rtAddStrings")))
                            "toClos")
                          (paren (commaseq)))
                        (cast (spaceseq (importid "foamj" "Word") (comment "Rec")) "t2")
                        (cast (spaceseq (importid "foamj" "Word") (comment "Rec")) "t3")))))
                (statement return)))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C1_addLevel0"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement
                          (declaration
                            (spaceseq)
                            (importid "foamj" "Clos")
                            (assign
                              "ret"
                              (apply
                                "c1_addLevel0"
                                (paren
                                  (commaseq
                                    "env"
                                    (apply (memref (arrayref "vals" 0) "asWord") (paren (commaseq)))))))))
                        (statement (spaceseq return "ret")))))))))
          (method
            (declaration
              (spaceseq private static)
              (importid "foamj" "Clos")
              "c1_addLevel0"
              (paren
                (commaseq
                  (declaration (spaceseq) (importid "foamj" "Env") "env0")
                  (declaration (spaceseq) (importid "foamj" "Word") "p0_domain")))
              (commaseq))
            (nlseq
              (nlseq
                (statement
                  (apply
                    "ccall_WxWW"
                    (paren
                      (commaseq
                        (apply
                          (memref
                            (apply
                              (memref (importid "foamj" "Globals") "getGlobal")
                              (paren (commaseq "domainAddNameFn!")))
                            "toClos")
                          (paren (commaseq)))
                        "p0_domain"
                        (apply
                          "ccall_WxA"
                          (paren
                            (commaseq
                              (apply
                                (memref
                                  (apply
                                    (memref (importid "foamj" "Globals") "getGlobal")
                                    (paren (commaseq "rtConstNameFn")))
                                  "toClos")
                                (paren (commaseq)))
                              (apply (memref "Rec" "toCharArray") (paren (commaseq))))))))))
                (statement
                  (apply
                    "ccall_WxWI"
                    (paren
                      (commaseq
                        (apply
                          (memref
                            (apply
                              (memref (importid "foamj" "Globals") "getGlobal")
                              (paren (commaseq "domainAddHash!")))
                            "toClos")
                          (paren (commaseq)))
                        "p0_domain"
                        316169045))))
                (statement
                  (spaceseq
                    return
                    (new
                      (apply
                        (importid "foamj" "Clos")
                        (paren (commaseq "env0" "C2_addLevel1")))
                      ())))))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C2_addLevel1"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement
                          (declaration
                            (spaceseq)
                            (importid "foamj" "Word")
                            (assign
                              "ret"
                              (apply
                                "c2_addLevel1"
                                (paren
                                  (commaseq
                                    "env"
                                    (apply (memref (arrayref "vals" 0) "asWord") (paren (commaseq)))
                                    (apply (memref (arrayref "vals" 1) "asWord") (paren (commaseq)))))))))
                        (statement
                          (spaceseq return (apply (memref "ret" "toValue") (paren (commaseq))))))))))))
          (method
            (declaration
              (spaceseq private static)
              (importid "foamj" "Word")
              "c2_addLevel1"
              (paren
                (commaseq
                  (declaration (spaceseq) (importid "foamj" "Env") "env0")
                  (declaration (spaceseq) (importid "foamj" "Word") "p0_domain")
                  (declaration (spaceseq) (importid "foamj" "Word") "p1_hashcode")))
              (commaseq))
            (nlseq
              (statement
                (declaration
                  (spaceseq)
                  (spaceseq (importid "foamj" "Word") (sqbracket (spaceseq)))
                  (commaseq "t2")))
              (statement
                (declaration
                  (spaceseq)
                  (importid "foamj" "Record")
                  (commaseq "t3" "t4" "t5")))
              (statement
                (declaration
                  (spaceseq)
                  (spaceseq int (sqbracket (spaceseq)))
                  (commaseq "t0" "t1")))
              (statement (declaration (spaceseq) int (commaseq "t6" "t7")))
              (statement
                (declaration
                  (spaceseq final)
                  (importid "foamj" "EnvRecord")
                  (assign "lvl0" (apply (memref "env0" "level") (paren (commaseq))))))
              (nlseq
                (statement (assign "t0" (new (arrayref int 2) ())))
                (statement (assign "t1" (new (arrayref int 2) ())))
                (statement
                  (assign "t2" (new (arrayref (importid "foamj" "Word") 2) ())))
                (statement
                  (apply
                    (memref "lvl0" "setField")
                    (paren
                      (commaseq
                        2
                        ""
                        (apply
                          (memref (memref (importid "foamj" "Value") "U") "fromSInt")
                          (paren (commaseq "p1_hashcode")))))))
                (statement
                  (apply
                    (memref "lvl0" "setField")
                    (paren
                      (commaseq
                        1
                        "new"
                        (new
                          (apply (importid "foamj" "Clos") (paren (commaseq "env0" "C3_new")))
                          ())))))
                (statement
                  (apply
                    (memref "lvl0" "setField")
                    (paren
                      (commaseq
                        0
                        "tag"
                        (new
                          (apply (importid "foamj" "Clos") (paren (commaseq "env0" "C4_tag")))
                          ())))))
                (statement
                  (assign
                    "t6"
                    (modulo
                      (plus
                        (apply
                          (memref
                            (apply (memref "lvl0" "getField") (paren (commaseq 2 "")))
                            "toSInt")
                          (paren (commaseq)))
                        447957760)
                      1073741789)))
                (statement
                  (assign
                    "t7"
                    (modulo
                      (plus
                        376332111
                        (shiftup
                          (and
                            (modulo
                              (plus
                                32236
                                (shiftup
                                  (and
                                    (modulo
                                      (plus
                                        (apply
                                          (memref
                                            (apply (memref "lvl0" "getField") (paren (commaseq 2 "")))
                                            "toSInt")
                                          (paren (commaseq)))
                                        74075968)
                                      1073741789)
                                    16777215)
                                  6))
                              1073741789)
                            16777215)
                          6))
                      1073741789)))
                (statement
                  (assign
                    "t3"
                    (new
                      (apply (importid "foamj" "Record") (paren (commaseq "FORMAT_5")))
                      ())))
                (statement
                  (apply
                    (memref "t3" "setField")
                    (paren
                      (commaseq
                        0
                        "size"
                        (apply
                          (memref (memref (importid "foamj" "Value") "U") "fromSInt")
                          (paren (commaseq 2)))))))
                (statement
                  (apply
                    (memref "t3" "setField")
                    (paren
                      (commaseq
                        1
                        "nsize"
                        (apply
                          (memref (memref (importid "foamj" "Value") "U") "fromSInt")
                          (paren (commaseq 2)))))))
                (statement
                  (apply
                    (memref "t3" "setField")
                    (paren
                      (commaseq
                        2
                        "values"
                        (apply
                          (memref
                            (cast (spaceseq (importid "foamj" "Word") (comment "Arr")) "t0")
                            "toValue")
                          (paren (commaseq)))))))
                (statement
                  (assign
                    "t4"
                    (new
                      (apply (importid "foamj" "Record") (paren (commaseq "FORMAT_5")))
                      ())))
                (statement
                  (apply
                    (memref "t4" "setField")
                    (paren
                      (commaseq
                        0
                        "size"
                        (apply
                          (memref (memref (importid "foamj" "Value") "U") "fromSInt")
                          (paren (commaseq 2)))))))
                (statement
                  (apply
                    (memref "t4" "setField")
                    (paren
                      (commaseq
                        1
                        "nsize"
                        (apply
                          (memref (memref (importid "foamj" "Value") "U") "fromSInt")
                          (paren (commaseq 2)))))))
                (statement
                  (apply
                    (memref "t4" "setField")
                    (paren
                      (commaseq
                        2
                        "values"
                        (apply
                          (memref
                            (cast (spaceseq (importid "foamj" "Word") (comment "Arr")) "t1")
                            "toValue")
                          (paren (commaseq)))))))
                (statement
                  (assign
                    "t5"
                    (new
                      (apply (importid "foamj" "Record") (paren (commaseq "FORMAT_5")))
                      ())))
                (statement
                  (apply
                    (memref "t5" "setField")
                    (paren
                      (commaseq
                        0
                        "size"
                        (apply
                          (memref (memref (importid "foamj" "Value") "U") "fromSInt")
                          (paren (commaseq 2)))))))
                (statement
                  (apply
                    (memref "t5" "setField")
                    (paren
                      (commaseq
                        1
                        "nsize"
                        (apply
                          (memref (memref (importid "foamj" "Value") "U") "fromSInt")
                          (paren (commaseq 2)))))))
                (statement
                  (apply
                    (memref "t5" "setField")
                    (paren
                      (commaseq
                        2
                        "values"
                        (apply
                          (memref
                            (cast (spaceseq (importid "foamj" "Word") (comment "Arr")) "t2")
                            "toValue")
                          (paren (commaseq)))))))
                (statement
                  (apply
                    "ccall_XxWRRR"
                    (paren
                      (commaseq
                        (apply
                          (memref
                            (apply
                              (memref (importid "foamj" "Globals") "getGlobal")
                              (paren (commaseq "domainAddExports!")))
                            "toClos")
                          (paren (commaseq)))
                        "p0_domain"
                        "t3"
                        "t4"
                        "t5"))))
                (statement (assign (arrayref "t0" 0) 318528389))
                (statement (assign (arrayref "t1" 0) "t6"))
                (statement
                  (assign
                    (arrayref "t2" 0)
                    (apply
                      (memref
                        (apply
                          (memref
                            (apply (memref "lvl0" "getField") (paren (commaseq 1 "new")))
                            "toClos")
                          (paren (commaseq)))
                        "asWord")
                      (paren (commaseq)))))
                (statement (assign (arrayref "t0" 1) 315787127))
                (statement (assign (arrayref "t1" 1) "t7"))
                (statement
                  (assign
                    (arrayref "t2" 1)
                    (apply
                      (memref
                        (apply
                          (memref
                            (apply (memref "lvl0" "getField") (paren (commaseq 0 "tag")))
                            "toClos")
                          (paren (commaseq)))
                        "asWord")
                      (paren (commaseq)))))
                (statement (spaceseq return "p0_domain"))))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C3_new"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement
                          (declaration
                            (spaceseq)
                            (importid "foamj" "Word")
                            (assign "ret" (apply "c3_new" (paren (commaseq "env"))))))
                        (statement
                          (spaceseq return (apply (memref "ret" "toValue") (paren (commaseq))))))))))))
          (method
            (declaration
              (spaceseq private static)
              (importid "foamj" "Word")
              "c3_new"
              (paren
                (commaseq (declaration (spaceseq) (importid "foamj" "Env") "env0")))
              (commaseq))
            (nlseq
              (statement
                (declaration (spaceseq) (importid "foamj" "Record") (commaseq "t0")))
              (nlseq
                (statement
                  (assign
                    "t0"
                    (new
                      (apply (importid "foamj" "Record") (paren (commaseq "FORMAT_6")))
                      ())))
                (statement
                  (apply
                    (memref "t0" "setField")
                    (paren
                      (commaseq 0 "t" (apply (memref 0 "toValue") (paren (commaseq)))))))
                (statement
                  (spaceseq
                    return
                    (cast (spaceseq (importid "foamj" "Word") (comment "Rec")) "t0")))))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C4_tag"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement
                          (declaration
                            (spaceseq)
                            (importid "foamj" "Word")
                            (assign
                              "ret"
                              (apply
                                "c4_tag"
                                (paren
                                  (commaseq
                                    "env"
                                    (apply (memref (arrayref "vals" 0) "asWord") (paren (commaseq)))))))))
                        (statement
                          (spaceseq return (apply (memref "ret" "toValue") (paren (commaseq))))))))))))
          (method
            (declaration
              (spaceseq private static)
              (importid "foamj" "Word")
              "c4_tag"
              (paren
                (commaseq
                  (declaration (spaceseq) (importid "foamj" "Env") "env0")
                  (declaration (spaceseq) (importid "foamj" "Word") "p0_x")))
              (commaseq))
            (nlseq
              (nlseq
                (statement
                  (spaceseq
                    return
                    (apply
                      (memref
                        (apply (memref "p0_x" "getField") (paren (commaseq 0 "t")))
                        "asWord")
                      (paren (commaseq)))))))))
        (method
          (declaration
            (spaceseq private static)
            void
            "ccall_XxWRRR"
            (paren
              (commaseq
                (declaration (spaceseq) (importid "foamj" "Clos") "_0")
                (declaration (spaceseq) (importid "foamj" "Word") "_1")
                (declaration (spaceseq) (importid "foamj" "Record") "_2")
                (declaration (spaceseq) (importid "foamj" "Record") "_3")
                (declaration (spaceseq) (importid "foamj" "Record") "_4")))
            (commaseq))
          (nlseq
            (statement
              (apply
                (memref "_0" "call")
                (paren
                  (commaseq
                    (apply (memref "_1" "toValue") (paren (commaseq)))
                    "_2"
                    "_3"
                    "_4"))))
            (statement return)))
        (method
          (declaration
            (spaceseq private static)
            (importid "foamj" "Word")
            "ccall_WxWW"
            (paren
              (commaseq
                (declaration (spaceseq) (importid "foamj" "Clos") "_0")
                (declaration (spaceseq) (importid "foamj" "Word") "_1")
                (declaration (spaceseq) (importid "foamj" "Word") "_2")))
            (commaseq))
          (nlseq
            (statement
              (declaration
                (spaceseq)
                (importid "foamj" "Value")
                (assign
                  "result"
                  (apply
                    (memref "_0" "call")
                    (paren
                      (commaseq
                        (apply (memref "_1" "toValue") (paren (commaseq)))
                        (apply (memref "_2" "toValue") (paren (commaseq)))))))))
            (statement
              (spaceseq
                return
                (apply (memref "result" "asWord") (paren (commaseq)))))))
        (method
          (declaration
            (spaceseq private static)
            (importid "foamj" "Word")
            "ccall_WxA"
            (paren
              (commaseq
                (declaration (spaceseq) (importid "foamj" "Clos") "_0")
                (declaration (spaceseq) "Object" "_1")))
            (commaseq))
          (nlseq
            (statement
              (declaration
                (spaceseq)
                (importid "foamj" "Value")
                (assign "result" (apply (memref "_0" "call") (paren (commaseq "_1"))))))
            (statement
              (spaceseq
                return
                (apply (memref "result" "asWord") (paren (commaseq)))))))
        (method
          (declaration
            (spaceseq private static)
            (importid "foamj" "Word")
            "ccall_WxWI"
            (paren
              (commaseq
                (declaration (spaceseq) (importid "foamj" "Clos") "_0")
                (declaration (spaceseq) (importid "foamj" "Word") "_1")
                (declaration (spaceseq) int "_2")))
            (commaseq))
          (nlseq
            (statement
              (declaration
                (spaceseq)
                (importid "foamj" "Value")
                (assign
                  "result"
                  (apply
                    (memref "_0" "call")
                    (paren
                      (commaseq
                        (apply (memref "_1" "toValue") (paren (commaseq)))
                        (apply
                          (memref (memref (importid "foamj" "Value") "U") "fromSInt")
                          (paren (commaseq "_2")))))))))
            (statement
              (spaceseq
                return
                (apply (memref "result" "asWord") (paren (commaseq)))))))
        (method
          (declaration
            (spaceseq private static)
            void
            "ccall_Xx"
            (paren
              (commaseq (declaration (spaceseq) (importid "foamj" "Clos") "_0")))
            (commaseq))
          (nlseq
            (statement (apply (memref "_0" "call") (paren (commaseq))))
            (statement return)))
        (method
          (declaration
            (spaceseq private static)
            (importid "foamj" "Word")
            "ccall_WxC"
            (paren
              (commaseq
                (declaration (spaceseq) (importid "foamj" "Clos") "_0")
                (declaration (spaceseq) (importid "foamj" "Clos") "_1")))
            (commaseq))
          (nlseq
            (statement
              (declaration
                (spaceseq)
                (importid "foamj" "Value")
                (assign "result" (apply (memref "_0" "call") (paren (commaseq "_1"))))))
            (statement
              (spaceseq
                return
                (apply (memref "result" "asWord") (paren (commaseq)))))))
        (method
          (declaration
            (spaceseq private static)
            void
            "ccall_XxWW"
            (paren
              (commaseq
                (declaration (spaceseq) (importid "foamj" "Clos") "_0")
                (declaration (spaceseq) (importid "foamj" "Word") "_1")
                (declaration (spaceseq) (importid "foamj" "Word") "_2")))
            (commaseq))
          (nlseq
            (statement
              (apply
                (memref "_0" "call")
                (paren
                  (commaseq
                    (apply (memref "_1" "toValue") (paren (commaseq)))
                    (apply (memref "_2" "toValue") (paren (commaseq)))))))
            (statement return)))))))
...*/
import foamj.EnvRecord;
import foamj.Record;
import foamj.Format;
import foamj.Word;
import foamj.Value;
import foamj.Env;
import foamj.Clos;
import foamj.Globals;
import foamj.Fn;
/** Generated by genjava - rectest
 **/
public class rectest {
    private static Format FORMAT_5 = new Format(3);
    private static Format FORMAT_6 = new Format(1);
    static Fn C0_rectest = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            c0_rectest(env);
            return null;
        }

    };
    private static void c0_rectest(Env env0) {
        Word [] t1;
        Record t2, t3;
        int [] t0;
        ccall_Xx(Globals.getGlobal("runtime").toClos());
        Globals.setGlobal("rectest", Globals.getGlobal("noOperation").toClos());
        Globals.setGlobal("rectest_Rec_743553378", ccall_WxC(Globals.getGlobal("domainMake").toClos(), new Clos(env0, C1_addLevel0)).toValue());
        t0 = new int[2];
        t1 = new Word[2];
        t0[0] = 318528389;
        t1[0] = "new".toCharArray();
        t0[1] = 315787127;
        t1[1] = "tag".toCharArray();
        t2 = new Record(FORMAT_5);
        t2.setField(0, "size", Value.U.fromSInt(2));
        t2.setField(1, "nsize", Value.U.fromSInt(2));
        t2.setField(2, "values", (Word /* Arr*/)t0.toValue());
        t3 = new Record(FORMAT_5);
        t3.setField(0, "size", Value.U.fromSInt(2));
        t3.setField(1, "nsize", Value.U.fromSInt(2));
        t3.setField(2, "values", (Word /* Arr*/)t1.toValue());
        ccall_XxWW(Globals.getGlobal("rtAddStrings").toClos(), (Word /* Rec*/)t2, (Word /* Rec*/)t3);
        return;
    }
    
    static Fn C1_addLevel0 = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c1_addLevel0(env, vals[0].asWord());
            return ret;
        }

    };
    private static Clos c1_addLevel0(Env env0, Word p0_domain) {
        ccall_WxWW(Globals.getGlobal("domainAddNameFn!").toClos(), p0_domain, ccall_WxA(Globals.getGlobal("rtConstNameFn").toClos(), "Rec".toCharArray()));
        ccall_WxWI(Globals.getGlobal("domainAddHash!").toClos(), p0_domain, 316169045);
        return new Clos(env0, C2_addLevel1);
    }
    
    static Fn C2_addLevel1 = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c2_addLevel1(env, vals[0].asWord(), vals[1].asWord());
            return ret.toValue();
        }

    };
    private static Word c2_addLevel1(Env env0, Word p0_domain, Word p1_hashcode) {
        Word [] t2;
        Record t3, t4, t5;
        int [] t0, t1;
        int t6, t7;
        final EnvRecord lvl0 = env0.level();
        t0 = new int[2];
        t1 = new int[2];
        t2 = new Word[2];
        lvl0.setField(2, "", Value.U.fromSInt(p1_hashcode));
        lvl0.setField(1, "new", new Clos(env0, C3_new));
        lvl0.setField(0, "tag", new Clos(env0, C4_tag));
        t6 = (lvl0.getField(2, "").toSInt() + 447957760)%1073741789;
        t7 = (376332111 + (((32236 + (((lvl0.getField(2, "").toSInt() + 74075968)%1073741789 & 16777215)<<6))%1073741789 & 16777215)<<6))%1073741789;
        t3 = new Record(FORMAT_5);
        t3.setField(0, "size", Value.U.fromSInt(2));
        t3.setField(1, "nsize", Value.U.fromSInt(2));
        t3.setField(2, "values", (Word /* Arr*/)t0.toValue());
        t4 = new Record(FORMAT_5);
        t4.setField(0, "size", Value.U.fromSInt(2));
        t4.setField(1, "nsize", Value.U.fromSInt(2));
        t4.setField(2, "values", (Word /* Arr*/)t1.toValue());
        t5 = new Record(FORMAT_5);
        t5.setField(0, "size", Value.U.fromSInt(2));
        t5.setField(1, "nsize", Value.U.fromSInt(2));
        t5.setField(2, "values", (Word /* Arr*/)t2.toValue());
        ccall_XxWRRR(Globals.getGlobal("domainAddExports!").toClos(), p0_domain, t3, t4, t5);
        t0[0] = 318528389;
        t1[0] = t6;
        t2[0] = lvl0.getField(1, "new").toClos().asWord();
        t0[1] = 315787127;
        t1[1] = t7;
        t2[1] = lvl0.getField(0, "tag").toClos().asWord();
        return p0_domain;
    }
    
    static Fn C3_new = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c3_new(env);
            return ret.toValue();
        }

    };
    private static Word c3_new(Env env0) {
        Record t0;
        t0 = new Record(FORMAT_6);
        t0.setField(0, "t", 0.toValue());
        return (Word /* Rec*/)t0;
    }
    
    static Fn C4_tag = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c4_tag(env, vals[0].asWord());
            return ret.toValue();
        }

    };
    private static Word c4_tag(Env env0, Word p0_x) {
        return p0_x.getField(0, "t").asWord();
    }
    
    private static void ccall_XxWRRR(Clos _0, Word _1, Record _2, Record _3, Record _4) {
        _0.call(_1.toValue(), _2, _3, _4);
        return;
    }
    
    private static Word ccall_WxWW(Clos _0, Word _1, Word _2) {
        Value result = _0.call(_1.toValue(), _2.toValue());
        return result.asWord();
    }
    
    private static Word ccall_WxA(Clos _0, Object _1) {
        Value result = _0.call(_1);
        return result.asWord();
    }
    
    private static Word ccall_WxWI(Clos _0, Word _1, int _2) {
        Value result = _0.call(_1.toValue(), Value.U.fromSInt(_2));
        return result.asWord();
    }
    
    private static void ccall_Xx(Clos _0) {
        _0.call();
        return;
    }
    
    private static Word ccall_WxC(Clos _0, Clos _1) {
        Value result = _0.call(_1);
        return result.asWord();
    }
    
    private static void ccall_XxWW(Clos _0, Word _1, Word _2) {
        _0.call(_1.toValue(), _2.toValue());
        return;
    }

}
