/*...
(nlseq
  (statement (spaceseq "import" (importid "foamj" "EnvRecord")))
  (statement (spaceseq "import" (importid "foamj" "MultiRecord")))
  (statement (spaceseq "import" (importid "foamj" "Format")))
  (statement (spaceseq "import" (importid "foamj" "Word")))
  (statement (spaceseq "import" (importid "foamj" "Value")))
  (statement (spaceseq "import" (importid "foamj" "Env")))
  (statement (spaceseq "import" (importid "foamj" "Clos")))
  (statement (spaceseq "import" (importid "foamj" "Globals")))
  (statement (spaceseq "import" (importid "foamj" "Fn")))
  (nlseq
    (javadoc "Generated by genjava - simple_j\\\\n")
    (class
      (spaceseq public)
      "simple_j"
      ()
      (commaseq)
      (nlseq
        (statement
          (declaration
            (spaceseq private static)
            (importid "foamj" "Format")
            (assign
              "FORMAT_5"
              (new (apply (importid "foamj" "Format") (paren (commaseq 2))) ()))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C0_simple__j"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement (apply "c0_simple__j" (paren (commaseq "env"))))
                        (statement (spaceseq return null)))))))))
          (method
            (declaration
              (spaceseq private static)
              void
              "c0_simple__j"
              (paren
                (commaseq (declaration (spaceseq) (importid "foamj" "Env") "env0")))
              (commaseq))
            (nlseq
              (nlseq
                (statement
                  (apply
                    "ccall_Xx"
                    (paren
                      (commaseq
                        (apply
                          (memref
                            (apply
                              (memref (importid "foamj" "Globals") "getGlobal")
                              (paren (commaseq "runtime")))
                            "toClos")
                          (paren (commaseq)))))))
                (statement
                  (apply
                    (memref (importid "foamj" "Globals") "setGlobal")
                    (paren
                      (commaseq
                        "simple_j"
                        (apply
                          (memref
                            (apply
                              (memref (importid "foamj" "Globals") "getGlobal")
                              (paren (commaseq "noOperation")))
                            "toClos")
                          (paren (commaseq)))))))
                (statement
                  (apply
                    (memref (importid "foamj" "Globals") "setGlobal")
                    (paren
                      (commaseq
                        "simple_j_t1_479859677"
                        (new
                          (apply (importid "foamj" "Clos") (paren (commaseq "env0" "C1_t1")))
                          ())))))
                (statement
                  (apply
                    (memref (importid "foamj" "Globals") "setGlobal")
                    (paren
                      (commaseq
                        "simple_j_t2_494407402"
                        (new
                          (apply (importid "foamj" "Clos") (paren (commaseq "env0" "C2_t2")))
                          ())))))
                (statement
                  (apply
                    (memref (importid "foamj" "Globals") "setGlobal")
                    (paren
                      (commaseq
                        "simple_j_t3_030021108"
                        (new
                          (apply (importid "foamj" "Clos") (paren (commaseq "env0" "C3_t3")))
                          ())))))
                (statement
                  (apply
                    (memref (importid "foamj" "Globals") "setGlobal")
                    (paren
                      (commaseq
                        "simple_j_t4_905089460"
                        (new
                          (apply (importid "foamj" "Clos") (paren (commaseq "env0" "C4_t4")))
                          ())))))
                (statement
                  (apply
                    (memref (importid "foamj" "Globals") "setGlobal")
                    (paren
                      (commaseq
                        "simple_j_t5_264916867"
                        (new
                          (apply (importid "foamj" "Clos") (paren (commaseq "env0" "C6_t5")))
                          ())))))
                (statement return)))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C1_t1"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement
                          (declaration
                            (spaceseq)
                            (importid "foamj" "Word")
                            (assign "ret" (apply "c1_t1" (paren (commaseq "env"))))))
                        (statement
                          (spaceseq return (apply (memref "ret" "toValue") (paren (commaseq))))))))))))
          (method
            (declaration
              (spaceseq private static)
              (importid "foamj" "Word")
              "c1_t1"
              (paren
                (commaseq (declaration (spaceseq) (importid "foamj" "Env") "env0")))
              (commaseq))
            (nlseq
              (nlseq
                (statement
                  (spaceseq
                    return
                    (apply
                      (memref (memref (importid "foamj" "Word") "U") "fromSInt")
                      (paren (commaseq 12)))))))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C2_t2"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement
                          (declaration
                            (spaceseq)
                            (importid "foamj" "Word")
                            (assign
                              "ret"
                              (apply
                                "c2_t2"
                                (paren
                                  (commaseq
                                    "env"
                                    (apply (memref (arrayref "vals" 0) "asWord") (paren (commaseq)))))))))
                        (statement
                          (spaceseq return (apply (memref "ret" "toValue") (paren (commaseq))))))))))))
          (method
            (declaration
              (spaceseq private static)
              (importid "foamj" "Word")
              "c2_t2"
              (paren
                (commaseq
                  (declaration (spaceseq) (importid "foamj" "Env") "env0")
                  (declaration (spaceseq) (importid "foamj" "Word") "p0_n")))
              (commaseq))
            (nlseq
              (nlseq
                (statement
                  (spaceseq
                    return
                    (apply
                      (memref (memref (importid "foamj" "Word") "U") "fromSInt")
                      (paren
                        (commaseq
                          (plus (apply (memref "p0_n" "toSInt") (paren (commaseq))) 1))))))))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C3_t3"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement
                          (apply
                            "c3_t3"
                            (paren
                              (commaseq
                                "env"
                                (apply (memref (arrayref "vals" 0) "asWord") (paren (commaseq)))
                                (apply (memref (arrayref "vals" 1) "asWord") (paren (commaseq)))))))
                        (statement (spaceseq return null)))))))))
          (method
            (declaration
              (spaceseq private static)
              (importid "foamj" "MultiRecord")
              "c3_t3"
              (paren
                (commaseq
                  (declaration (spaceseq) (importid "foamj" "Env") "env0")
                  (declaration (spaceseq) (importid "foamj" "Word") "p0_a")
                  (declaration (spaceseq) (importid "foamj" "Word") "p1_b")))
              (commaseq))
            (nlseq
              (statement (declaration (spaceseq) int (commaseq "t0" "t1")))
              (nlseq
                (statement
                  (assign
                    "t0"
                    (plus
                      (apply (memref "p0_a" "toSInt") (paren (commaseq)))
                      (apply (memref "p1_b" "toSInt") (paren (commaseq))))))
                (statement
                  (assign
                    "t1"
                    (minus
                      (apply (memref "p0_a" "toSInt") (paren (commaseq)))
                      (apply (memref "p1_b" "toSInt") (paren (commaseq))))))
                (statement
                  (declaration
                    (spaceseq)
                    (importid "foamj" "MultiRecord")
                    (assign
                      "var0"
                      (new
                        (apply (importid "foamj" "MultiRecord") (paren (commaseq "FORMAT_5")))
                        ()))))
                (statement
                  (apply
                    (memref "var0" "setField")
                    (paren
                      (commaseq
                        0
                        ""
                        (apply
                          (memref
                            (apply
                              (memref (memref (importid "foamj" "Word") "U") "fromSInt")
                              (paren (commaseq "t0")))
                            "toValue")
                          (paren (commaseq)))))))
                (statement
                  (apply
                    (memref "var0" "setField")
                    (paren
                      (commaseq
                        1
                        ""
                        (apply
                          (memref
                            (apply
                              (memref (memref (importid "foamj" "Word") "U") "fromSInt")
                              (paren (commaseq "t1")))
                            "toValue")
                          (paren (commaseq)))))))
                (statement (spaceseq return "var0"))))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C4_t4"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement
                          (declaration
                            (spaceseq)
                            (importid "foamj" "Clos")
                            (assign
                              "ret"
                              (apply
                                "c4_t4"
                                (paren
                                  (commaseq
                                    "env"
                                    (apply (memref (arrayref "vals" 0) "asWord") (paren (commaseq)))))))))
                        (statement (spaceseq return "ret")))))))))
          (method
            (declaration
              (spaceseq private static)
              (importid "foamj" "Clos")
              "c4_t4"
              (paren
                (commaseq
                  (declaration (spaceseq) (importid "foamj" "Env") "env0")
                  (declaration (spaceseq) (importid "foamj" "Word") "p0_a")))
              (commaseq))
            (nlseq
              (statement
                (declaration
                  (spaceseq final)
                  (importid "foamj" "EnvRecord")
                  (assign "lvl0" (apply (memref "env0" "level") (paren (commaseq))))))
              (nlseq
                (statement
                  (apply
                    (memref "lvl0" "setField")
                    (paren
                      (commaseq
                        0
                        "a"
                        (apply (memref "p0_a" "toValue") (paren (commaseq)))))))
                (statement
                  (spaceseq
                    return
                    (new
                      (apply (importid "foamj" "Clos") (paren (commaseq "env0" "C5_t4")))
                      ())))))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C5_t4"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement
                          (declaration
                            (spaceseq)
                            (importid "foamj" "Word")
                            (assign
                              "ret"
                              (apply
                                "c5_t4"
                                (paren
                                  (commaseq
                                    "env"
                                    (apply (memref (arrayref "vals" 0) "asWord") (paren (commaseq)))))))))
                        (statement
                          (spaceseq return (apply (memref "ret" "toValue") (paren (commaseq))))))))))))
          (method
            (declaration
              (spaceseq private static)
              (importid "foamj" "Word")
              "c5_t4"
              (paren
                (commaseq
                  (declaration (spaceseq) (importid "foamj" "Env") "env0")
                  (declaration (spaceseq) (importid "foamj" "Word") "p0_x")))
              (commaseq))
            (nlseq
              (statement
                (declaration (spaceseq) (importid "foamj" "Word") (commaseq "t0")))
              (statement
                (declaration
                  (spaceseq final)
                  (importid "foamj" "Env")
                  (assign "env1" (apply (memref "env0" "parent") (paren (commaseq))))))
              (statement
                (declaration
                  (spaceseq final)
                  (importid "foamj" "EnvRecord")
                  (assign "lvl1" (apply (memref "env1" "level") (paren (commaseq))))))
              (nlseq
                (statement
                  (assign
                    "t0"
                    (apply
                      (memref
                        (apply (memref "lvl1" "getField") (paren (commaseq 0 "a")))
                        "asWord")
                      (paren (commaseq)))))
                (statement
                  (spaceseq
                    return
                    (apply
                      (memref (memref (importid "foamj" "Word") "U") "fromSInt")
                      (paren
                        (commaseq
                          (plus
                            (apply (memref "t0" "toSInt") (paren (commaseq)))
                            (apply (memref "p0_x" "toSInt") (paren (commaseq)))))))))))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C6_t5"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement
                          (declaration
                            (spaceseq)
                            (importid "foamj" "Clos")
                            (assign
                              "ret"
                              (apply
                                "c6_t5"
                                (paren
                                  (commaseq
                                    "env"
                                    (apply (memref (arrayref "vals" 0) "toClos") (paren (commaseq)))))))))
                        (statement (spaceseq return "ret")))))))))
          (method
            (declaration
              (spaceseq private static)
              (importid "foamj" "Clos")
              "c6_t5"
              (paren
                (commaseq
                  (declaration (spaceseq) (importid "foamj" "Env") "env0")
                  (declaration (spaceseq) (importid "foamj" "Clos") "p0_f")))
              (commaseq))
            (nlseq
              (statement
                (declaration
                  (spaceseq final)
                  (importid "foamj" "EnvRecord")
                  (assign "lvl0" (apply (memref "env0" "level") (paren (commaseq))))))
              (nlseq
                (statement
                  (apply (memref "lvl0" "setField") (paren (commaseq 0 "f" "p0_f"))))
                (statement
                  (spaceseq
                    return
                    (new
                      (apply (importid "foamj" "Clos") (paren (commaseq "env0" "C7_t5")))
                      ())))))))
        (nlseq
          (statement
            (declaration
              (spaceseq static)
              (importid "foamj" "Fn")
              (assign
                "C7_t5"
                (new
                  (apply (importid "foamj" "Fn") (paren (commaseq)))
                  (nlseq
                    (method
                      (declaration
                        (spaceseq public)
                        (importid "foamj" "Value")
                        "ocall"
                        (paren
                          (commaseq
                            (declaration (spaceseq) (importid "foamj" "Env") "env")
                            (declaration
                              (spaceseq)
                              (spaceseq (importid "foamj" "Value") |...|)
                              "vals")))
                        (commaseq))
                      (nlseq
                        (statement
                          (declaration
                            (spaceseq)
                            (importid "foamj" "Word")
                            (assign
                              "ret"
                              (apply
                                "c7_t5"
                                (paren
                                  (commaseq
                                    "env"
                                    (apply (memref (arrayref "vals" 0) "asWord") (paren (commaseq)))))))))
                        (statement
                          (spaceseq return (apply (memref "ret" "toValue") (paren (commaseq))))))))))))
          (method
            (declaration
              (spaceseq private static)
              (importid "foamj" "Word")
              "c7_t5"
              (paren
                (commaseq
                  (declaration (spaceseq) (importid "foamj" "Env") "env0")
                  (declaration (spaceseq) (importid "foamj" "Word") "p0_n")))
              (commaseq))
            (nlseq
              (statement
                (declaration
                  (spaceseq)
                  (importid "foamj" "Word")
                  (commaseq "t0" "t1")))
              (statement
                (declaration
                  (spaceseq final)
                  (importid "foamj" "Env")
                  (assign "env1" (apply (memref "env0" "parent") (paren (commaseq))))))
              (statement
                (declaration
                  (spaceseq final)
                  (importid "foamj" "EnvRecord")
                  (assign "lvl1" (apply (memref "env1" "level") (paren (commaseq))))))
              (nlseq
                (statement
                  (declaration
                    (spaceseq)
                    (importid "foamj" "MultiRecord")
                    (assign
                      "var0"
                      (apply
                        "ccall_WWxW"
                        (paren
                          (commaseq
                            (apply
                              (memref
                                (apply (memref "lvl1" "getField") (paren (commaseq 0 "f")))
                                "toClos")
                              (paren (commaseq)))
                            "p0_n"))))))
                (statement
                  (assign
                    "t0"
                    (apply
                      (memref
                        (apply (memref "var0" "getField") (paren (commaseq 0 "")))
                        "asWord")
                      (paren (commaseq)))))
                (statement
                  (assign
                    "t1"
                    (apply
                      (memref
                        (apply (memref "var0" "getField") (paren (commaseq 1 "")))
                        "asWord")
                      (paren (commaseq)))))
                (statement
                  (spaceseq
                    return
                    (apply
                      (memref (memref (importid "foamj" "Word") "U") "fromSInt")
                      (paren
                        (commaseq
                          (plus
                            (apply (memref "t0" "toSInt") (paren (commaseq)))
                            (apply (memref "t1" "toSInt") (paren (commaseq)))))))))))))
        (method
          (declaration
            (spaceseq private static)
            (importid "foamj" "MultiRecord")
            "ccall_WWxW"
            (paren
              (commaseq
                (declaration (spaceseq) (importid "foamj" "Clos") "_0")
                (declaration (spaceseq) (importid "foamj" "Word") "_1")))
            (commaseq))
          (nlseq
            (statement
              (declaration
                (spaceseq)
                (importid "foamj" "Value")
                (assign
                  "result"
                  (apply
                    (memref "_0" "call")
                    (paren (commaseq (apply (memref "_1" "toValue") (paren (commaseq)))))))))
            (statement
              (spaceseq
                return
                (apply (memref "result" "toMulti") (paren (commaseq)))))))
        (method
          (declaration
            (spaceseq private static)
            void
            "ccall_Xx"
            (paren
              (commaseq (declaration (spaceseq) (importid "foamj" "Clos") "_0")))
            (commaseq))
          (nlseq
            (statement (apply (memref "_0" "call") (paren (commaseq))))
            (statement return)))))))
...*/
import foamj.EnvRecord;
import foamj.MultiRecord;
import foamj.Format;
import foamj.Word;
import foamj.Value;
import foamj.Env;
import foamj.Clos;
import foamj.Globals;
import foamj.Fn;
/** Generated by genjava - simple_j
 **/
public class simple_j {
    private static Format FORMAT_5 = new Format(2);
    static Fn C0_simple__j = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            c0_simple__j(env);
            return null;
        }

    };
    private static void c0_simple__j(Env env0) {
        ccall_Xx(Globals.getGlobal("runtime").toClos());
        Globals.setGlobal("simple_j", Globals.getGlobal("noOperation").toClos());
        Globals.setGlobal("simple_j_t1_479859677", new Clos(env0, C1_t1));
        Globals.setGlobal("simple_j_t2_494407402", new Clos(env0, C2_t2));
        Globals.setGlobal("simple_j_t3_030021108", new Clos(env0, C3_t3));
        Globals.setGlobal("simple_j_t4_905089460", new Clos(env0, C4_t4));
        Globals.setGlobal("simple_j_t5_264916867", new Clos(env0, C6_t5));
        return;
    }
    
    static Fn C1_t1 = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c1_t1(env);
            return ret.toValue();
        }

    };
    private static Word c1_t1(Env env0) {
        return Word.U.fromSInt(12);
    }
    
    static Fn C2_t2 = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c2_t2(env, vals[0].asWord());
            return ret.toValue();
        }

    };
    private static Word c2_t2(Env env0, Word p0_n) {
        return Word.U.fromSInt(p0_n.toSInt() + 1);
    }
    
    static Fn C3_t3 = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            c3_t3(env, vals[0].asWord(), vals[1].asWord());
            return null;
        }

    };
    private static MultiRecord c3_t3(Env env0, Word p0_a, Word p1_b) {
        int t0, t1;
        t0 = p0_a.toSInt() + p1_b.toSInt();
        t1 = p0_a.toSInt() - p1_b.toSInt();
        MultiRecord var0 = new MultiRecord(FORMAT_5);
        var0.setField(0, "", Word.U.fromSInt(t0).toValue());
        var0.setField(1, "", Word.U.fromSInt(t1).toValue());
        return var0;
    }
    
    static Fn C4_t4 = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c4_t4(env, vals[0].asWord());
            return ret;
        }

    };
    private static Clos c4_t4(Env env0, Word p0_a) {
        final EnvRecord lvl0 = env0.level();
        lvl0.setField(0, "a", p0_a.toValue());
        return new Clos(env0, C5_t4);
    }
    
    static Fn C5_t4 = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c5_t4(env, vals[0].asWord());
            return ret.toValue();
        }

    };
    private static Word c5_t4(Env env0, Word p0_x) {
        Word t0;
        final Env env1 = env0.parent();
        final EnvRecord lvl1 = env1.level();
        t0 = lvl1.getField(0, "a").asWord();
        return Word.U.fromSInt(t0.toSInt() + p0_x.toSInt());
    }
    
    static Fn C6_t5 = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c6_t5(env, vals[0].toClos());
            return ret;
        }

    };
    private static Clos c6_t5(Env env0, Clos p0_f) {
        final EnvRecord lvl0 = env0.level();
        lvl0.setField(0, "f", p0_f);
        return new Clos(env0, C7_t5);
    }
    
    static Fn C7_t5 = new Fn() { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c7_t5(env, vals[0].asWord());
            return ret.toValue();
        }

    };
    private static Word c7_t5(Env env0, Word p0_n) {
        Word t0, t1;
        final Env env1 = env0.parent();
        final EnvRecord lvl1 = env1.level();
        MultiRecord var0 = ccall_WWxW(lvl1.getField(0, "f").toClos(), p0_n);
        t0 = var0.getField(0, "").asWord();
        t1 = var0.getField(1, "").asWord();
        return Word.U.fromSInt(t0.toSInt() + t1.toSInt());
    }
    
    private static MultiRecord ccall_WWxW(Clos _0, Word _1) {
        Value result = _0.call(_1.toValue());
        return result.toMulti();
    }
    
    private static void ccall_Xx(Clos _0) {
        _0.call();
        return;
    }

}
