#!/usr/bin/env perl

use common::sense;
use Text::Wrap;

my @remotes = `git remote -v`;
exit 1 if $!;

my $token = `git config github.token`;
if (not $token) {
   say "Please set your github token:";
   say "  git config --global github.token <token>";
   exit 1;
}


for (@remotes) {
   if (m!\t(?:git://|git@)github\.com[:/]([^/]+)/([^.]+)\.git \(fetch\)!) {
      require Net::GitHub;
      my $gh = new Net::GitHub (access_token => $token);

      $gh->set_default_user_repo ($1, $2);

      my $issues = $gh->issue->repos_issues;

      if (@ARGV) {
         for (grep { $_->{number} ~~ @ARGV } @$issues) {
            say "$_->{number}. $_->{title}";
            say (wrap "   ", "   ", $_->{body});
         }
      } else {
         for (sort { $a->{number} <=> $b->{number} }
              grep { $_->{state} eq "open" }
              @$issues) {
            say "$_->{number}. $_->{title}";
         }
      }

      last
   }
}
