#

exes := unicl platform

s := ../../src

cfiles_unicl := unicl2.c 

cfiles_platform := platform.c


libfiles := $(s)/file.c $(s)/fname.c $(s)/opsys.c $(s)/store.c $(s)/memclim.c \
	$(s)/fluid.c $(s)/btree.c $(s)/stdc.c $(s)/strops.c \
	$(s)/debug.c $(s)/xfloat.c $(s)/buffer.c $(s)/timer.c \
	$(s)/util.c $(s)/list.c $(s)/format.c $(s)/cfgfile.c

libobjs := $(patsubst %,$(builddir)/$(thisdir)/%,$(notdir $(libfiles)))

$(libobjs): $(builddir)/$(thisdir)/%.o: %.c

