#!/usr/bin/env perl

use strict;

open my $fh, '<', $ARGV[0]
   or die "$ARGV[0]: $!";

my @uniq;
while (my $dep = <$fh>) {
   chomp $dep; next unless $dep;
   push @uniq, $dep unless grep { $_ eq $dep } @uniq;
}

print "@uniq";
